intolc/urls.py
from django.urls import path
from intolc.views import *

urlpatterns = [
	path('', IndexView.as_view(template_name='intolc/index.html'), name='index'),
	path('typzanr/add/', TypZanrCreate.as_view(), name='typzanr'),
	path('typzanr/<int:pk>/delete', TypZanrDelete.as_view(), name='typzanr-delete'),
	path('album/add/', AlbumCreate.as_view(), name='album'),
	path('album/<int:pk>/delete', AlbumDelete.as_view(), name='album-delete'),
	path('skladba/add/', SkladbaCreate.as_view(), name='skladba'),
	path('skladba/<int:pk>/delete', SkladbaDelete.as_view(), name='skladba-delete'),
	path('albumskladba/<int:pk>/delete', SkladbaDelete.as_view(), name='skladba-delete'),
	path('albumskladba/add/', AlbumSkladbaCreate.as_view(), name='albumskladba'),
	path('albumskladba/<int:pk>/delete', AlbumSkladbaDelete.as_view(), name='albumskladba-delete'),
	path('typnarodnost/add/', TypNarodnostCreate.as_view(), name='typnarodnost'),
	path('TypNarodnost/<int:pk>/delete', TypNarodnostDelete.as_view(), name='typnarodnost-delete'),
	path('interpret/add/', InterpretCreate.as_view(), name='interpret'),
	path('interpret/<int:pk>/delete', InterpretDelete.as_view(), name='interpret-delete'),
]

olc/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('intolc.urls')),
]

intolc/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class TypZanr(models.Model):
	nazev = models.CharField(max_length=50, unique=True)

	def __str__(self):
		return self.nazev

# 	def get_absolute_url(self):
#		return reverse('typ-zanr-detail', kwargs={'pk': self.pk})


class Album(models.Model):
	typ_zanr = models.ForeignKey(TypZanr, on_delete=models.CASCADE)
	nazev = models.CharField(max_length=50)
	datum_vydani = models.DateField(blank=True)

	class Meta:
		ordering = ['nazev', '-datum_vydani']

	def __str__(self):
		return self.nazev


class Skladba(models.Model):
	nazev = models.CharField(max_length=50)
	delka = models.CharField(max_length=8)
	# album = models.ManyToManyField(Album, through='AlbumSkladba', blank=True)

	def __str__(self):
		return self.nazev


class AlbumSkladba(models.Model):
	cislo_stopy = models.PositiveSmallIntegerField()
	album = models.ForeignKey(Album, on_delete=models.CASCADE)
	skladba = models.ForeignKey(Skladba, on_delete=models.CASCADE)

	class Meta:
		ordering = ['cislo_stopy']

	def __str__(self):
		return f'{self.cislo_stopy}'


class TypNarodnost(models.Model):
	nazev = models.CharField(max_length=20)

	def __str__(self):
		return self.nazev


class Interpret(models.Model):
	nazev = models.CharField(max_length=50)
	typ_narodnost = models.ForeignKey(TypNarodnost, on_delete=models.CASCADE)
	album = models.ManyToManyField(Album)

	class Meta:
		ordering = ['nazev']

	def __str__(self):
		return self.nazev

intolc/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.views.generic.edit import CreateView, DeleteView
from django.urls import reverse_lazy
from .models import *


# Create your views here.
class IndexView(TemplateView):
    template_name = 'inolc/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['album_query'] = Album.objects.all().order_by('nazev')
        return context


class TypZanrCreate(CreateView):
    model = TypZanr
    fields = '__all__'
    name = model.__name__.casefold()
    template_name = f'intolc/add_form.html'
    success_url = f'/{name}/add'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['query'] = __class__.model.objects.all().order_by('nazev')
        context['delete'] = f'{__class__.name}-delete'
        return context


class TypZanrDelete(DeleteView):
    model = TypZanr
    template_name = 'intolc/delete.html'
    success_url = reverse_lazy(model.__name__.casefold())


class AlbumCreate(CreateView):
    model = Album
    fields = '__all__'
    name = model.__name__.casefold()
    template_name = f'intolc/add_form.html'
    success_url = f'/{name}/add'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['query'] = __class__.model.objects.all().order_by('nazev')
        context['delete'] = f'{__class__.name}-delete'
        return context


class AlbumDelete(DeleteView):
    model = Album
    name = model.__name__.casefold()
    template_name = f'intolc/add_form.html'
    success_url = reverse_lazy(model.__name__.casefold())


class SkladbaCreate(CreateView):
    model = Skladba
    fields = '__all__'
    name = model.__name__.casefold()
    template_name = f'intolc/add_form.html'
    success_url = f'/{name}/add'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['query'] = __class__.model.objects.all().order_by('nazev')
        context['delete'] = f'{__class__.name}-delete'
        return context


class SkladbaDelete(DeleteView):
    model = Skladba
    name = model.__name__.casefold()
    template_name = 'intolc/delete.html'
    success_url = reverse_lazy(model.__name__.casefold())


class AlbumSkladbaCreate(CreateView):
    model = AlbumSkladba
    fields = '__all__'
    name = model.__name__.casefold()
    template_name = f'intolc/add_form.html'
    success_url = f'/{name}/add'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['query'] = __class__.model.objects.all()
        context['delete'] = f'{__class__.name}-delete'
        return context


class AlbumSkladbaDelete(DeleteView):
    model = AlbumSkladba
    name = model.__name__.casefold()
    template_name = 'intolc/delete.html'
    success_url = reverse_lazy(model.__name__.casefold())


class TypNarodnostCreate(CreateView):
    model = TypNarodnost
    fields = '__all__'
    name = model.__name__.casefold()
    template_name = f'intolc/add_form.html'
    success_url = f'/{name}/add'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['query'] = __class__.model.objects.all().order_by('nazev')
        context['delete'] = f'{__class__.name}-delete'
        return context


class TypNarodnostDelete(DeleteView):
    model = TypNarodnost
    template_name = 'intolc/delete.html'
    success_url = reverse_lazy(model.__name__.casefold())


class InterpretCreate(CreateView):
    model = Interpret
    fields = '__all__'
    name = model.__name__.casefold()
    template_name = f'intolc/add_form.html'
    success_url = f'/{name}/add'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['query'] = __class__.model.objects.all().order_by('nazev')
        context['delete'] = f'{__class__.name}-delete'
        return context


class InterpretDelete(DeleteView):
    model = Interpret
    template_name = 'intolc/delete.html'
    success_url = reverse_lazy(model.__name__.casefold())

intolc/templates/intolc/add_form.html
{%extends 'intolc/base.html'%}

{%block title%}{{header}}{%endblock%}

{%block content%}
	{% include "intolc/form_snippets.html" with form=form query=query delete=delete %}
{%endblock%}

intolc/templates/intolc/base.html
<!DOCTYPE html>
{% load static %}

<html lang="cs-cz">
    <head>
        <meta charset="utf-8" />
        <title>{%block title%}EMCS šablona{%endblock%}</title>
        <link rel="stylesheet" type="text/css" href="{%static 'intolc/css/main.css'%}">
        <script type="text/javascript" src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
        <script type="text/javascript" src="{%static 'intolc/js/main.js'%}"></script>
    </head>

    <body>
	   <div class="header">
			{% load static %}
			<img src="{% static "intolc/img/olc_logo.svg" %}" alt="company logo"/>
			<h2><a href={%url 'index'%}>HOME</a></h2>
		</div>
		{%block content%}
			<h2>base header</h2>
		{%endblock%}
    </body>
</html>

intolc/templates/intolc/delete.html
{%extends 'intolc/base.html'%}

{%block title%}olc confirm delete{%endblock%}

{%block content%}
    <!--...-->
	<form method="post">{% csrf_token %}
		<p>Skutečně chceš smazat "{{ object }}"?</p>
		<input type="submit" value="Smazat">
	</form>
{%endblock%}

intolc/templates/intolc/form_snippets.html
<div class="forms">

	<form method="post">{%csrf_token%}
		{{form.as_ul}}
		<input type="submit" value="vytvořit" />
	</form>

	<h4>Přehled:</h4>

	<ul>
		{%for i in query%}
			{%if i.nazev%}
				<li>{{i.nazev}} - <a href="{%url delete i.pk%}">smazat</a></li>
			{%else%}
				<li>{{i.cislo_stopy}}|{{i.skladba.nazev}}|{{i.skladba.delka}} - <a href="{%url delete i.pk%}">smazat</a></li>
			{%endif%}
		{%empty%}
			<span>Není k dispozici</span>
		{%endfor%}
	</ul>
</div>

intolc/templates/intolc/index.html
{%extends 'intolc/base.html'%}

{%block title%}olc homework{%endblock%}

{%block content%}
	<div class="forms">
		<a href={%url 'typzanr'%}>Žánr</a>
		<a href={%url 'album'%}>Album</a>
		<a href={%url 'skladba'%}>Skladba</a>
		<a href={%url 'albumskladba'%}>AlbumSkladba</a>
		<a href={%url 'typnarodnost'%}>Národnost</a>
		<a href={%url 'interpret'%}>Interpret</a>

		<ul id="prehled">
			<li id>Název alba - žánr - datum vydání</li>
		{%for album in album_query%}
			<li>{{album.nazev}} - {{album.typ_zanr.nazev}} - {{album.datum_vydani}}
				{%if album.interpret_set%}
					({{album.interpret_set.first.nazev}} -
					{{album.interpret_set.first.typ_narodnost.nazev}})
				{%endif%}
				<ul class="sublist">
				{%if album.albumskladba_set%}
					{%for skladba in  album.albumskladba_set.all%}
						<li>{{skladba.cislo_stopy}} - {{skladba.skladba.nazev}} - {{skladba.skladba.delka}}</li>
					{%empty%}
						<li>Prázdné album</li>
					{%endfor%}
				{%endif%}
				</ul>
			</li>
		{%empty%}
			<li>Žádné album nebylo nalezeno v DB</li>
		{%endfor%}
		</ul>
	</div>
{%endblock%}